---
apiVersion: v1
kind: Service
metadata:
  name: weather-csv
  labels:
    app: weather
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: weather-csv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-csv
  labels:
    app: weather
spec:
  selector:
    matchLabels:
      app: weather-csv
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-csv
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: 418330922897.dkr.ecr.ap-northeast-1.amazonaws.com/weather-csv
          name: weather-csv
          env:
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8080"
            - name: SERVER_HOST
              value: "weather-store"
            - name: SERVER_PORT
              value: "80"
          ports:
            - containerPort: 8080
              name: weather-csv

